import Head from 'next/head'
import { Footer } from '../../components/footer/Footer'
import { Header } from '../../components/header/Header'
import styles from '../../styles/Home.module.scss'
import articleStyles from '../../styles/Article.module.scss'

function Article() {
    return (
        <div className={styles.container}>
      <Head>
        <title>NextJS News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <article className={articleStyles.article}>
            <h2>Single article</h2>
            <p>Lorum ipselum bla-bla...</p>
        </article>
      </main>
      <Footer />
    </div>
    )
}
export async function getStaticPaths() {
    // Return a list of possible value for id
}

export async function getStaticProps(params: any) {
    console.log(params)
    // Fetch necessary data for the blog post using params.id
}

export default Article;