import Head from 'next/head'
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import styles from '../../styles/Home.module.scss'
import articleStyles from '../../styles/Article.module.scss'
import { useRouter } from 'next/router'

function singleArticle() {
    const router = useRouter()
    const { id } = router.query

    return (
        <div className={styles.container}>
      <Head>
        <title>NextJS News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <article className={articleStyles.article}>
            <h2>Single article {id}</h2>
            <p>Lorum ipselum bla-bla...</p>
        </article>
      </main>
      <Footer />
    </div>
    )
}

export default singleArticle;