import React, { FunctionComponent } from 'react'
import Head from 'next/head'
import { Footer } from '@/components/footer/Footer'
import { Header } from '@/components/header/Header'
import { useRouter } from 'next/router'
import styles from '@/styles/index.module.scss'
import articleStyles from './Article.module.scss'

export const Article: FunctionComponent = () => {
    const router = useRouter()
    const { id } = router.query

    return (
        <div className={styles.container}>
          <Head>
            <title>NextJS News App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <Header />
            <article className={articleStyles.article}>
                <h2>Single article {id}</h2>
                <p>Lorum ipselum bla-bla...</p>
            </article>
          </main>
          <Footer />
        </div>
      )
}
