import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Learning App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <article className={styles.article}>
          <h2>Some header</h2>
          <section>
            <p>
              Some content.
            </p>
          </section>
        </article>
      </main>

      <Footer />
    </div>
  )
}

export default Home
