import type { NextPage } from 'next'
import Head from 'next/head'
import useArticle from '../lib/useArticle'
import Articles from '../components/Articles'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  //const { articles, isLoading, isError } = useArticle('home')
  //if (articles) console.log(articles);
  //if (isError) console.log('error');
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Learning App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Articles />
      </main>

      <Footer />
    </div>
  )
}

export default Home
