import React, { FunctionComponent } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useArticles } from '../../hooks/useArticles'
import { Footer } from '../footer/Footer'
import { Header } from '../header/Header'
import styles from "./ArticlesList.module.scss"
import globalStyles from '../../styles/index.module.scss'
import { convertDateString } from "../../lib/utils"
import Link from 'next/link'
import { useRouter } from 'next/router'
import type { Article } from '../../models/Article'

/* Return list of articles by incoming category */
export const ArticlesList: FunctionComponent = () => {
    const { articles, isLoading, isError } = useArticles('home');//Get articles
    //const router = useRouter()
    
    let content;
    if (isError) content = <div className={styles.errorMessage}>Error message</div>;
    if (isLoading) content = <div className={styles.loader}>Loading...</div>;
    if (articles){
        content = articles.results.map((article: Article) => {
            return <article key={article.short_url} className={styles.article}>
                <div className={styles.sectionWrapper}>
                    <span className={styles.sectionTitle}>{article.section}</span>
                </div>
                <div className={styles.dateWrapper}>
                    <span>{convertDateString(article.published_date)}</span>
                </div>
                <h3 className={styles.titleWrapper}>{article.title}</h3>
                <section className={styles.bodyWrapper}>
                    <p>{article.abstract}</p>
                </section>
                <div className={styles.imageWrapper}>
                    <Image src={article.multimedia[1].url} alt={article.title} width={article.multimedia[1].width} height={article.multimedia[1].height}/>
                </div> 
            </article>;
        });
    }
    return (
        <div className={globalStyles.container}>
            <Head>
                <title>NextJS News App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={globalStyles.main}>
                <Header />
                {content}
            </main>
            <Footer />
        </div>
    )
}